### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by theSuess** [paviliondev/discourse-pavilion#1]
Hello there,
I'd like to use this plugin as a starting point for our discourse instance.

As this repository does not contain a license file and I was unable to find more information about licensing etc. it would be great to get some clarification on this - thanks!

**Comment by angusmcleod** [comment]
Hey @theSuess,

Sure, you're welcome to use it and thanks for the prod about the license. I've added a the GNU v2 and a copyright notice (which doesn't restrict your use of the code in anyway whatsoever; it just guards againist it from being republished under another name).

If you make any improvements, we're more than willing to review PRs. This plugin is still early stage, and we plan to make a number of improvements to it.

**Comment by theSuess** [comment]
Thanks for the quick update!
